version: '3.4'

networks:
  backend:

services:
  pokemondb:
    container_name: pokemon-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - 8001:1433
  pokemonwebapi:
    container_name: pokemon-api
    image: ${DOCKER_REGISTRY-}pokemonwebapi
    build:
      context: .
      dockerfile: PokemonWebApi/Dockerfile
    networks:
      - backend
    ports:
      - 8002:8080
    environment:
      - DB_HOST=pokemondb
      - DB_NAME=pokemon
      - DB_SA_PASSWORD=password@12345#
    depends_on:
      - pokemondb