name: Run Tests

on:
  push:
    branches:
      - master  # Change this to your main branch name or the branch you want to trigger the tests on
  pull_request:
    branches:
      - master  # Change this to your main branch name or the branch you want to trigger the tests on

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "password@12345#"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "curl -f http://localhost:1433 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'  # Adjust this version based on your project

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and run unit tests
      run: dotnet test PokemonWebApi.Unit.Tests/PokemonWebApi.Unit.Tests.csproj --no-build --verbosity normal

    - name: Build and run integration tests
      run: dotnet test PokemonWebApi.Integration.Tests/PokemonWebApi.Integration.Tests.csproj --no-build --verbosity normal
